version: "3.8"

services:
  web:
    build: .
    container_name: todo-web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html

  database:
    image: mysql:8.0.35
    container_name: todo-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: todo
      MYSQL_USER: system
      MYSQL_PASSWORD: system
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./app/schema.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql
